### ISSUE TITLE
Getting HMR Errors in Dev

### ISSUE THREAD

**Issue by jhubbardsf** [oslabs-beta/Svelcro#41]
I built and added this to Brave to try and play around it with it but I'm getting a bunch of HRM errors and no Svelcro tab in any SvelteKit apps.

Error from browser console:
```
(index):22 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Header'
    |     property '$$' -> object with constructor 'Object'
    --- property 'hmr_cmp' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.set ((index):22:29)
    at HTMLDocument.<anonymous> ((index):76:23)
    at dispatch_dev (index.mjs:1984:14)
    at new Images (_Images.svelte? [sm]:16:67)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<_Images> (proxy.js:349:11)
    at create_fragment (index.svelte? [sm]:3:39)
    at init (index.mjs:1891:37)
```

Not sure what other information would be helpful to you. 

Edit: I confirmed this also happened in chrome for me. The Svelcro tab does not appear in dev tools and in extensions I get the following error logs.

Chrome: (Version 102.0.5005.61 (Official Build) (arm64))
MacOS: 12.0.1. 
NPM: 8.5.1. 

chrome://extensions logs

Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

**Comment by AlexRMU** [comment]
The same things on chrome

**Comment by rankind94** [comment]
Thanks for the comments, will be taking a look at this soon and get back with a fix!
